package Karol;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Label;
import com.vaadin.ui.AbsoluteLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DetaliedUI extends AbsoluteLayout {
    protected Label tempTitle;
    protected Label tempGenere;
    protected Label tempLenght;
    protected Label tempLanguage;
    protected Label tempRelease;
    protected Label tempDirector;
    protected Label tempDescription;
    protected Label movieTitle;
    protected Label movieGenere;
    protected Label movieLenght;
    protected Label movieLanguage;
    protected Label movieReleased;
    protected Label movieDirector;
    protected Label movieDescription;

    public DetaliedUI() {
        Design.read(this);
    }
}
